; Asterisk REST Interface

[general]
enabled = yes
pretty = no
allowed_origins = http://localhost:3000,https://api.allojoy.gn

[allojoy]
type = user
read_only = no
password = ${ARI_PASSWORD}
password_format = plain
